language: c
sudo: false

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.stack

matrix:
  include:
    - env: GHCVER=7.10.3 STACK_YAML=stack.yaml
      compiler: ": #GHC 8.0.2"
    - env: GHCVER=8.0.1 STACK_YAML=stack-head.yaml
      compiler: ": #GHC 8.2.1"

before_install:
 # install Stack
 - mkdir -p ~/.local/bin
 - export PATH=$HOME/.local/bin:$PATH
 - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - stack setup

install:
 - stack --version
 - stack build --only-dependencies --flag ghc-typelits-presburger:examples

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 -  stack --no-terminal --skip-ghc-check test --flag ghc-typelits-presburger:examples

# Check that the resulting source distribution can be built & installed.
# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
# `cabal install --force-reinstalls dist/*-*.tar.gz`
# EOF
