resolver: lts-6.8
packages:
- '.'
- location:
    git: https://github.com/konn/equational-reasoning-in-haskell.git
    commit: 323bca8a9d52a1de361bd18d7f9b0856718d5712
  extra-dep: true

extra-deps:
- th-desugar-1.6
- singletons-2.1

flags: {}
extra-package-dbs: []
